[alias]
b = "build"
t = "test"
r = "run"

[build]
rustflags = [
    "--cfg",
    "tokio_unstable"
]

[target.x86_64-unknown-linux-musl]


[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C",
    "target-feature=+crt-static",
]
